version: "3.8"

services:
  # deno_postgres:
  #   image: postgres:17.2-alpine
  #   container_name: deno_postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root1234
  #     POSTGRES_DB: deno_postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  deno_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deno_api
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_PATH: /app/data/sqlite.db
    volumes:
      # - .:/app
      - deno_data:/app/data
    command:
      [
        "run",
        "--allow-net",
        "--allow-read",
        "--allow-write",
        "--allow-env",
        "--import-map=deno.json",
        "server.ts",
      ]
volumes:
  deno_data:
