version: "3.8"

services:
  deno_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deno_api
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_PATH: /app/data/sqlite.db
    volumes:
      - ./data:/app/data
    command:
      [
        "run",
        "--allow-net",
        "--allow-read",
        "--allow-write",
        "--allow-env",
        "--import-map=deno.json",
        "server.ts",
      ]
volumes:
  deno_data:
